### ISSUE TITLE
When i run release mode this error occure

### ISSUE THREAD

**Issue by cgowthamanmca** [nabto/nabto-android-rtsp-wip#1]
E/AndroidRuntime(32302): java.lang.NoSuchMethodError: no static method "Lcom/nabto/api/NabtoStatus;.fromInteger(I)Lcom/nabto/api/NabtoStatus;"
E/AndroidRuntime(32302):        at com.nabto.api.NabtoCApiWrapper.nabtoSetStaticResourceDir(Native Method)
E/AndroidRuntime(32302):        at com.nabto.api.b.b(Unknown Source:8)
E/AndroidRuntime(32302):        at e.a.c.a.j$a.a(Unknown Source:17)
E/AndroidRuntime(32302):        at io.flutter.embedding.engine.f.c.i(Unknown Source:18)
E/AndroidRuntime(32302):        at io.flutter.embedding.engine.f.c.j(Unknown Source:20)
E/AndroidRuntime(32302):        at io.flutter.embedding.engine.f.c.k(Unknown Source:0)
E/AndroidRuntime(32302):        at io.flutter.embedding.engine.f.a.run(Unknown Source:12)
E/AndroidRuntime(32302):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(32302):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(32302):        at android.os.Looper.loop(Looper.java:245)
E/AndroidRuntime(32302):        at android.app.ActivityThread.main(ActivityThread.java:8024)
E/AndroidRuntime(32302):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32302):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(32302):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by gammelby** [comment]
This is an unsupported repo for an initial version of an old RTSP client for our legacy platform Nabto 4/Micro. The problem sounds as one that was fixed in the meantime in an updated Nabto API - and the project comes bundled with an old version. Try to replace the aar file with the latest Android API aar file. Moreover, I _highly_ recommend skipping Nabto 4/Micro altogether and using Nabto 5/Edge instead: This is the future platform where all new features will be added - and is better in almost every aspect. You can see a comparison here: https://docs.nabto.com/developer/guides/concepts/overview/edge-vs-micro.html. If you have any questions in this regard, don't hesitate to contact us! Chat on www or mail to support@nabto.com.

**Comment by cgowthamanmca** [comment]
@gammelby  I am updated latest arr version still same issue occured. Is any thing need to add proguard android?

**Comment by gammelby** [comment]
Ah, in fact we have seen trouble in release build before as ProGuard erroneously strips used functions. Please try to disable.

**Comment by cgowthamanmca** [comment]
@gammelby  I am implement now  Nabto 4/Micro its working fine but i need to implement  Nabto 5/Edge could you help me for this any example for nabto edge using streaming video.can you provide that.

**Comment by gammelby** [comment]
@cgowthamanmca as promised in the www chat, the Edge thermostat example is now made public here: https://github.com/nabto/thermostat-demo-android - as mentioned this demonstrates how to connect and pair using Nabto 5/Edge. You can then replace the thermostat control view with a video player view. Our next demo app will be an actual video player - but it will take a while until it is ready.
